# Background opacity (1.0 = opaque, 0.0 = fully transparent)
background_opacity 0.6

# Optional: blur behind terminal (requires compositor like picom)
enable_window_blur yes
blur_radius 5.0
include ~/.cache/wal/colors-kitty.conf
allow_remote_control socket-only
listen_on unix:/tmp/kitty-{kitty_pid}
